/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Bias {
  Off = 0,
  PullDown = 1,
  PullUp = 2
}
export const enum Level {
  Low = 0,
  High = 1
}
export declare class Gpio {
  constructor()
  /**
  * Get a GPIO pin by its number.
  */
  get(pin: number): Pin
}
export declare class Pin {
  /**
  * The pin number of the GPIO input pin.
  */
  get pin(): number
  /**
  * Converts the GPIO pin to an `InputPin` and sets the disables the pull-up/pull-down resistors.
  */
  intoInput(): InputPin
  /**
  * Converts the GPIO pin to an `InputPin` and enables the pull-down resistor.
  */
  intoInputPulldown(): InputPin
  /**
  * Converts the GPIO pin to an `InputPin` and enables the pull-up resistor.
  */
  intoInputPullup(): InputPin
  /**
  * Converts the GPIO pin to an `OutputPin`.
  */
  intoOutput(): OutputPin
  /**
  * Converts the GPIO pin to an `OutputPin` and sets the initial state to low.
  */
  intoOutputLow(): OutputPin
  /**
  * Converts the GPIO pin to an `OutputPin` and sets the initial state to high.
  */
  intoOutputHigh(): OutputPin
}
export declare class OutputPin {
  /**
  * The pin number of the GPIO output pin.
  */
  get pin(): number
  /**
  * Sets the GPIO output pin to the specified value.
  */
  set state(level: Level)
  /**
  * Whether the GPIO output pin is set to low.
  */
  get isSetLow(): boolean
  /**
  * Whether the GPIO output pin is set to high.
  */
  get isSetHigh(): boolean
  /**
  * Sets the GPIO output pin to low.
  */
  setLow(): void
  /**
  * Sets the GPIO output pin to high.
  */
  setHigh(): void
  /**
  * Toggles the GPIO output pin state.
  */
  toggle(): void
}
export declare class InputPin {
  /**
  * The pin number of the GPIO input pin.
  */
  get pin(): number
  /**
  * The state of the GPIO input pin.
  */
  get state(): Level
  /**
  * Whether the GPIO input pin is set to low.
  */
  get isSetLow(): boolean
  /**
  * Whether the GPIO input pin is set to high.
  */
  get isSetHigh(): boolean
  /**
  * Configures the built-in pull-up or pull-down resistor for the GPIO input pin.
  */
  setBias(bias: Bias): void
}
